apiVersion: v1
kind: Service
metadata:
  name: k8sagent
  namespace: k8sagent
  labels:
    app: k8sagent
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: k8sagent 